-- Additional workflow templates to make the site more populated
-- Adding 14 more workflows for a total of 20

INSERT OR REPLACE INTO workflows (
    id, slug, name, description, category_id, tags, repo_id, file_path,
    github_url, raw_url, dsl_content, content_hash, readme_content,
    dify_version, app_mode, node_count, node_types, has_knowledge_base,
    has_tool_nodes, has_valid_positions, download_count, view_count,
    works_count, broken_count, github_updated_at, synced_at, created_at, updated_at
) VALUES
    -- Chatbot Example
    (
        '77777777-7777-7777-7777-777777777777',
        'shamspias-customer-support-bot',
        'Customer Support Chatbot',
        'Intelligent customer service bot with FAQ handling and escalation',
        'chatbots',
        '["Chatbot", "Customer Support", "FAQ", "Help Desk"]',
        'shamspias',
        'flows/customer-support-bot.yaml',
        'https://github.com/shamspias/awesome-dify-agents/blob/main/flows/customer-support-bot.yaml',
        'https://raw.githubusercontent.com/shamspias/awesome-dify-agents/main/flows/customer-support-bot.yaml',
        'app:\n  mode: chatflow\n  description: Advanced customer support chatbot\n\nnodes:\n  - id: start\n    type: start\n    data:\n      title: Welcome\n  - id: intent\n    type: llm\n    data:\n      title: Understand Intent\n  - id: faq\n    type: knowledge\n    data:\n      title: Search FAQ\n  - id: human\n    type: condition\n    data:\n      title: Need Human?\n  - id: ticket\n    type: tool\n    data:\n      title: Create Ticket\n  - id: answer\n    type: llm\n    data:\n      title: Provide Answer\n  - id: end\n    type: end\n    data:\n      title: Complete',
        'faq123xyz789',
        'Comprehensive customer support solution with intelligent routing',
        '1.5',
        'chatflow',
        8,
        '["start", "llm", "knowledge", "condition", "tool", "end"]',
        1,
        1,
        1,
        3200,
        8500,
        124,
        5,
        '2024-12-07T08:00:00Z',
        datetime('now'),
        datetime('now'),
        datetime('now')
    ),

    -- Automation Example
    (
        '88888888-8888-8888-8888-888888888888',
        'tomatio-email-automation',
        'Email Automation Workflow',
        'Automated email processing and response system',
        'automation',
        '["Automation", "Email", "Productivity", "Communication"]',
        'tomatio',
        'email-automation.yaml',
        'https://github.com/Tomatio13/DifyWorkFlowGenerator/blob/main/email-automation.yaml',
        'https://raw.githubusercontent.com/Tomatio13/DifyWorkFlowGenerator/main/email-automation.yaml',
        'app:\n  mode: workflow\n  description: Automated email processing system\n\nnodes:\n  - id: start\n    type: start\n    data:\n      title: New Email\n  - id: classify\n    type: llm\n    data:\n      title: Classify Email\n  - id: extract\n    type: llm\n    data:\n      title: Extract Info\n  - id: draft\n    type: llm\n    data:\n      title: Draft Response\n  - id: send\n    type: tool\n    data:\n      title: Send Email\n  - id: end\n    type: end\n    data:\n      title: Processed',
        'email456abc012',
        'Intelligent email automation with classification and auto-response',
        '1.3',
        'workflow',
        6,
        '["start", "llm", "tool", "end"]',
        0,
        1,
        1,
        1800,
        4900,
        67,
        8,
        '2024-12-07T09:30:00Z',
        datetime('now'),
        datetime('now'),
        datetime('now')
    ),

    -- Development Example
    (
        '99999999-9999-9999-9999-999999999999',
        'svcvit-main-code-review-assistant',
        'Code Review Assistant',
        'AI-powered code review tool for multiple programming languages',
        'development',
        '["Code Review", "Development", "Quality Assurance", "Git"]',
        'svcvit-main',
        'DSL/code-review-assistant.yaml',
        'https://github.com/svcvit/Awesome-Dify-Workflow/blob/main/DSL/code-review-assistant.yaml',
        'https://raw.githubusercontent.com/svcvit/Awesome-Dify-Workflow/main/DSL/code-review-assistant.yaml',
        'app:\n  mode: workflow\n  description: Automated code review and suggestions\n\nnodes:\n  - id: start\n    type: start\n    data:\n      title: Code Input\n  - id: analyze\n    type: code\n    data:\n      title: Static Analysis\n  - id: review\n    type: llm\n    data:\n      title: AI Review\n  - id: score\n    type: code\n    data:\n      title: Calculate Score\n  - id: report\n    type: template\n    data:\n      title: Generate Report\n  - id: end\n    type: end\n    data:\n      title: Complete',
        'review789def345',
        'Comprehensive code review with AI-powered insights',
        '1.4',
        'workflow',
        6,
        '["start", "code", "llm", "template", "end"]',
        0,
        1,
        1,
        2100,
        5600,
        89,
        3,
        '2024-12-07T10:15:00Z',
        datetime('now'),
        datetime('now'),
        datetime('now')
    ),

    -- More Content Creation
    (
        'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
        'zhouhui-blog-post-generator',
        'Blog Post Generator',
        'Generate SEO-optimized blog posts on any topic',
        'content',
        '["Blog", "SEO", "Writing", "Content Marketing"]',
        'zhouhui',
        'blog-generator-workflow.yaml',
        'https://github.com/wwwzhouhui/dify-for-dsl/blob/master/blog-generator-workflow.yaml',
        'https://raw.githubusercontent.com/wwwzhouhui/dify-for-dsl/master/blog-generator-workflow.yaml',
        'app:\n  mode: workflow\n  description: SEO-optimized blog content generator\n\nnodes:\n  - id: start\n    type: start\n    data:\n      title: Topic\n  - id: research\n    type: tool\n    data:\n      title: Research Topic\n  - id: outline\n    type: llm\n    data:\n      title: Create Outline\n  - id: write\n    type: llm\n    data:\n      title: Write Content\n  - id: seo\n    type: llm\n    data:\n      title: Optimize SEO\n  - id: format\n    type: template\n    data:\n      title: Format Post\n  - id: end\n    type: end\n    data:\n      title: Published',
        'blog234ghi567',
        'Professional blog post generation with SEO optimization',
        '1.2',
        'workflow',
        7,
        '["start", "tool", "llm", "template", "end"]',
        0,
        1,
        1,
        2800,
        7200,
        156,
        12,
        '2024-12-07T11:45:00Z',
        datetime('now'),
        datetime('now'),
        datetime('now')
    ),

    -- More MCP
    (
        'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
        'svcvit-main-mcp-file-manager',
        'MCP File Manager',
        'File system operations through Model Context Protocol',
        'mcp',
        '["MCP", "File System", "Operations", "Tool"]',
        'svcvit-main',
        'DSL/mcp-file-manager.yaml',
        'https://github.com/svcvit/Awesome-Dify-Workflow/blob/main/DSL/mcp-file-manager.yaml',
        'https://raw.githubusercontent.com/svcvit/Awesome-Dify-Workflow/main/DSL/mcp-file-manager.yaml',
        'app:\n  mode: workflow\n  description: File management via MCP\n\nnodes:\n  - id: start\n    type: start\n    data:\n      title: File Operation\n  - id: command\n    type: tool\n    data:\n      title: Execute Command\n      provider: mcp-file-system\n  - id: verify\n    type: tool\n    data:\n      title: Verify Result\n  - id: end\n    type: end\n    data:\n      title: Complete',
        'file345jkl890',
        'Direct file system operations through MCP protocol',
        '1.1',
        'workflow',
        4,
        '["start", "tool", "end"]',
        0,
        1,
        1,
        950,
        2400,
        34,
        2,
        '2024-12-07T13:00:00Z',
        datetime('now'),
        datetime('now'),
        datetime('now')
    ),

    -- More Agents
    (
        'cccccccc-cccc-cccc-cccc-cccccccccccc',
        'bannylon-virtual-assistant',
        'Personal Virtual Assistant',
        'AI assistant for daily tasks and scheduling',
        'agents',
        '["Assistant", "Scheduling", "Tasks", "Productivity"]',
        'bannylon',
        'virtual-assistant.yaml',
        'https://github.com/BannyLon/DifyAIA/blob/main/virtual-assistant.yaml',
        'https://raw.githubusercontent.com/BannyLon/DifyAIA/main/virtual-assistant.yaml',
        'app:\n  mode: agent\n  description: Personal AI assistant\n\nnodes:\n  - id: start\n    type: start\n    data:\n      title: Task Request\n  - id: understand\n    type: llm\n    data:\n      title: Understand Task\n  - id: calendar\n    type: tool\n    data:\n      title: Check Calendar\n  - id: plan\n    type: llm\n    data:\n      title: Create Plan\n  - id: execute\n    type: tool\n    data:\n      title: Execute Task\n  - id: confirm\n    type: llm\n    data:\n      title: Confirm Completion\n  - id: end\n    type: end\n    data:\n      title: Done',
        'assist456mno123',
        'Intelligent personal assistant with task management',
        '1.6',
        'agent',
        7,
        '["start", "llm", "tool", "end"]',
        1,
        1,
        1,
        3200,
        8900,
        198,
        7,
        '2024-12-07T14:20:00Z',
        datetime('now'),
        datetime('now'),
        datetime('now')
    ),

    -- More RAG
    (
        'dddddddd-dddd-dddd-dddd-dddddddddddd',
        'winson-knowledge-base-qa',
        'Knowledge Base Q&A',
        'Multi-document knowledge base with intelligent search',
        'rag',
        '["Knowledge Base", "Q&A", "Search", "Documents"]',
        'winson',
        'knowledge-base-qa.yaml',
        'https://github.com/Winson-030/dify-DSL/blob/main/knowledge-base-qa.yaml',
        'https://raw.githubusercontent.com/Winson-030/dify-DSL/main/knowledge-base-qa.yaml',
        'app:\n  mode: workflow\n  description: Advanced knowledge base Q&A\n\nnodes:\n  - id: start\n    type: start\n    data:\n      title: Question\n  - id: search\n    type: knowledge\n    data:\n      title: Search Knowledge\n  - id: rank\n    type: llm\n    data:\n      title: Rank Results\n  - id: answer\n    type: llm\n    data:\n      title: Generate Answer\n  - id: sources\n    type: template\n    data:\n      title: Format with Sources\n  - id: end\n    type: end\n    data:\n      title: Response',
        'kb567nop890',
        'Sophisticated knowledge base with source attribution',
        '1.3',
        'workflow',
        6,
        '["start", "knowledge", "llm", "template", "end"]',
        1,
        0,
        1,
        1900,
        5100,
        73,
        4,
        '2024-12-07T15:30:00Z',
        datetime('now'),
        datetime('now'),
        datetime('now')
    ),

    -- More Translation
    (
        'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee',
        'pgshen-real-time-translator',
        'Real-time Translator',
        'Live translation for conversations and meetings',
        'translation',
        '["Real-time", "Translation", "Meetings", "Conversation"]',
        'pgshen',
        'realtime-translator.yaml',
        'https://github.com/PGshen/dify-app-template/blob/main/realtime-translator.yaml',
        'https://raw.githubusercontent.com/PGshen/dify-app-template/main/realtime-translator.yaml',
        'app:\n  mode: workflow\n  description: Real-time translation service\n\nnodes:\n  - id: start\n    type: start\n    data:\n      title: Speech Input\n  - id: transcribe\n    type: tool\n    data:\n      title: Speech to Text\n  - id: translate\n    type: llm\n    data:\n      title: Translate Text\n  - id: synthesize\n    type: tool\n    data:\n      title: Text to Speech\n  - id: end\n    type: end\n    data:\n      title: Audio Output',
        'real678qrs123',
        'Real-time speech translation with voice output',
        '1.4',
        'workflow',
        5,
        '["start", "tool", "llm", "end"]',
        0,
        1,
        1,
        2400,
        6200,
        91,
        6,
        '2024-12-07T16:45:00Z',
        datetime('now'),
        datetime('now'),
        datetime('now')
    ),

    -- More Data Analysis
    (
        'ffffffff-ffff-ffff-ffff-ffffffffffff',
        'zhouhui-data-visualization',
        'Data Visualization Builder',
        'Create interactive charts and dashboards from data',
        'data',
        '["Visualization", "Charts", "Dashboards", "Analytics"]',
        'zhouhui',
        'data-viz-workflow.yaml',
        'https://github.com/wwwzhouhui/dify-for-dsl/blob/master/data-viz-workflow.yaml',
        'https://raw.githubusercontent.com/wwwzhouhui/dify-for-dsl/master/data-viz-workflow.yaml',
        'app:\n  mode: workflow\n  description: Automated data visualization\n\nnodes:\n  - id: start\n    type: start\n    data:\n      title: Upload Data\n  - id: analyze\n    type: code\n    data:\n      title: Analyze Data\n  - id: chart\n    type: llm\n    data:\n      title: Select Charts\n  - id: generate\n    type: tool\n    data:\n      title: Generate Visuals\n  - id: dashboard\n    type: template\n    data:\n      title: Create Dashboard\n  - id: end\n    type: end\n    data:\n      title: Complete',
        'viz789stu456',
        'Automated data visualization with intelligent chart selection',
        '1.5',
        'workflow',
        6,
        '["start", "code", "llm", "tool", "template", "end"]',
        0,
        1,
        1,
        1700,
        4300,
        54,
        3,
        '2024-12-07T18:00:00Z',
        datetime('now'),
        datetime('now'),
        datetime('now')
    ),

    -- More Chatbots
    (
        'gggggggg-gggg-gggg-gggg-gggggggggggg',
        'shamspias-shopping-assistant',
        'Shopping Assistant Bot',
        'E-commerce assistant with product recommendations',
        'chatbots',
        '["E-commerce", "Shopping", "Recommendations", "Sales"]',
        'shamspias',
        'flows/shopping-assistant.yaml',
        'https://github.com/shamspias/awesome-dify-agents/blob/main/flows/shopping-assistant.yaml',
        'https://raw.githubusercontent.com/shamspias/awesome-dify-agents/main/flows/shopping-assistant.yaml',
        'app:\n  mode: chatflow\n  description: Smart shopping assistant\n\nnodes:\n  - id: start\n    type: start\n    data:\n      title: Welcome\n  - id: category\n    type: llm\n    data:\n      title: Identify Category\n  - id: search\n    type: tool\n    data:\n      title: Search Products\n  - id: recommend\n    type: llm\n    data:\n      title: Make Recommendations\n  - id: compare\n    type: llm\n    data:\n      title: Compare Options\n  - id: end\n    type: end\n    data:\n      title: Decision',
        'shop890tuv567',
        'Intelligent shopping assistant with product discovery',
        '1.3',
        'chatflow',
        6,
        '["start", "llm", "tool", "end"]',
        1,
        1,
        1,
        2600,
        6800,
        112,
        9,
        '2024-12-07T19:15:00Z',
        datetime('now'),
        datetime('now'),
        datetime('now')
    ),

    -- More Automation
    (
        'hhhhhhhh-hhhh-hhhh-hhhh-hhhhhhhhhhhh',
        'tomatio-social-media-scheduler',
        'Social Media Scheduler',
        'Automate social media posting across platforms',
        'automation',
        '["Social Media", "Scheduling", "Marketing", "Automation"]',
        'tomatio',
        'social-scheduler.yaml',
        'https://github.com/Tomatio13/DifyWorkFlowGenerator/blob/main/social-scheduler.yaml',
        'https://raw.githubusercontent.com/Tomatio13/DifyWorkFlowGenerator/main/social-scheduler.yaml',
        'app:\n  mode: workflow\n  description: Social media automation\n\nnodes:\n  - id: start\n    type: start\n    data:\n      title: New Post\n  - id: content\n    type: llm\n    data:\n      title: Generate Content\n  - id: schedule\n    type: tool\n    data:\n      title: Schedule Posts\n  - id: post\n    type: tool\n    data:\n      title: Auto Publish\n  - id: analyze\n    type: tool\n    data:\n      title: Track Performance\n  - id: end\n    type: end\n    data:\n      title: Complete',
        'social901wxy234',
        'Complete social media automation with analytics',
        '1.2',
        'workflow',
        6,
        '["start", "llm", "tool", "end"]',
        0,
        1,
        1,
        2200,
        5800,
        85,
        11,
        '2024-12-07T20:30:00Z',
        datetime('now'),
        datetime('now'),
        datetime('now')
    ),

    -- More Development
    (
        'iiiiiiii-iiii-iiii-iiii-iiiiiiiiiiii',
        'svcvit-main-api-test-generator',
        'API Test Generator',
        'Generate automated tests for REST APIs',
        'development',
        '["API", "Testing", "Automation", "Quality"]',
        'svcvit-main',
        'DSL/api-test-generator.yaml',
        'https://github.com/svcvit/Awesome-Dify-Workflow/blob/main/DSL/api-test-generator.yaml',
        'https://raw.githubusercontent.com/svcvit/Awesome-Dify-Workflow/main/DSL/api-test-generator.yaml',
        'app:\n  mode: workflow\n  description: Automated API test generation\n\nnodes:\n  - id: start\n    type: start\n    data:\n      title: API Spec\n  - id: parse\n    type: llm\n    data:\n      title: Parse Endpoints\n  - id: generate\n    type: llm\n    data:\n      title: Generate Tests\n  - id: validate\n    type: code\n    data:\n      title: Validate Tests\n  - id: export\n    type: template\n    data:\n      title: Export Code\n  - id: end\n    type: end\n    data:\n      title: Complete',
        'test012yzab567',
        'Automated test generation for REST APIs',
        '1.1',
        'workflow',
        6,
        '["start", "llm", "code", "template", "end"]',
        0,
        1,
        1,
        1400,
        3500,
        42,
        1,
        '2024-12-07T21:45:00Z',
        datetime('now'),
        datetime('now'),
        datetime('now')
    ),

    -- Extra Content Creation
    (
        'jjjjjjjj-jjjj-jjjj-jjjj-jjjjjjjjjjjj',
        'bannylon-video-script-writer',
        'Video Script Writer',
        'Create engaging video scripts for YouTube and TikTok',
        'content',
        '["Video", "Script", "YouTube", "TikTok", "Content"]',
        'bannylon',
        'video-script-writer.yaml',
        'https://github.com/BannyLon/DifyAIA/blob/main/video-script-writer.yaml',
        'https://raw.githubusercontent.com/BannyLon/DifyAIA/main/video-script-writer.yaml',
        'app:\n  mode: workflow\n  description: Video script generation\n\nnodes:\n  - id: start\n    type: start\n    data:\n      title: Topic\n  - id: research\n    type: tool\n    data:\n      title: Trend Research\n  - id: outline\n    type: llm\n    data:\n      title: Script Outline\n  - id: write\n    type: llm\n    data:\n      title: Write Script\n  - id: optimize\n    type: llm\n    data:\n      title: Optimize for Platform\n  - id: end\n    type: end\n    data:\n      title: Ready',
        'script123bcd890',
        'Platform-optimized video script generation',
        '1.0',
        'workflow',
        5,
        '["start", "tool", "llm", "end"]',
        0,
        1,
        1,
        3100,
        8200,
        167,
        14,
        '2024-12-07T23:00:00Z',
        datetime('now'),
        datetime('now'),
        datetime('now')
    ),

    -- Extra Data Analysis
    (
        'kkkkkkkk-kkkk-kkkk-kkkk-kkkkkkkkkkkk',
        'winson-sentiment-analyzer',
        'Sentiment Analysis Tool',
        'Analyze sentiment in text data and reviews',
        'data',
        '["Sentiment Analysis", "NLP", "Text Analytics", "Opinion Mining"]',
        'winson',
        'sentiment-analyzer.yaml',
        'https://github.com/Winson-030/dify-DSL/blob/main/sentiment-analyzer.yaml',
        'https://raw.githubusercontent.com/Winson-030/dify-DSL/main/sentiment-analyzer.yaml',
        'app:\n  mode: workflow\n  description: Text sentiment analysis\n\nnodes:\n  - id: start\n    type: start\n    data:\n      title: Input Text\n  - id: preprocess\n    type: code\n    data:\n      title: Preprocess Text\n  - id: analyze\n    type: llm\n    data:\n      title: Analyze Sentiment\n  - id: categorize\n    type: llm\n    data:\n      title: Categorize\n  - id: visualize\n    type: tool\n    data:\n      title: Create Charts\n  - id: report\n    type: template\n    data:\n      title: Generate Report\n  - id: end\n    type: end\n    data:\n      title: Complete',
        'sent234cde345',
        'Advanced sentiment analysis with visualization',
        '1.2',
        'workflow',
        7,
        '["start", "code", "llm", "tool", "template", "end"]',
        0,
        1,
        1,
        1600,
        4100,
        61,
        2,
        '2024-12-08T00:15:00Z',
        datetime('now'),
        datetime('now'),
        datetime('now')
    );

-- Update category counts to reflect new workflows
UPDATE categories SET workflow_count = 3 WHERE id = 'mcp';      -- Added 2 more
UPDATE categories SET workflow_count = 3 WHERE id = 'agents';   -- Added 2 more
UPDATE categories SET workflow_count = 2 WHERE id = 'rag';      -- Added 1 more
UPDATE categories SET workflow_count = 3 WHERE id = 'content';  -- Added 2 more
UPDATE categories SET workflow_count = 1 WHERE id = 'translation'; -- No new
UPDATE categories SET workflow_count = 3 WHERE id = 'data';     -- Added 2 more
UPDATE categories SET workflow_count = 2 WHERE id = 'automation'; -- Added 1 more
UPDATE categories SET workflow_count = 3 WHERE id = 'development'; -- Added 2 more
UPDATE categories SET workflow_count = 2 WHERE id = 'chatbots'; -- Added 1 more