-- Sample workflow data for testing
-- Insert some example workflows to show data on the frontend

INSERT OR REPLACE INTO workflows (
    id, slug, name, description, category_id, tags, repo_id, file_path,
    github_url, raw_url, dsl_content, content_hash, readme_content,
    dify_version, app_mode, node_count, node_types, has_knowledge_base,
    has_tool_nodes, has_valid_positions, download_count, view_count,
    works_count, broken_count, github_updated_at, synced_at, created_at, updated_at
) VALUES
    -- MCP Server Example
    (
        '11111111-1111-1111-1111-111111111111',
        'svcvit-main-mcp-browser-navigation',
        'MCP Browser Navigation',
        'Integrate browser control capabilities with Dify using Model Context Protocol',
        'mcp',
        '["MCP", "Browser", "Web Automation", "Tool Integration"]',
        'svcvit-main',
        'DSL/mcp-browser-navigation.yaml',
        'https://github.com/svcvit/Awesome-Dify-Workflow/blob/main/DSL/mcp-browser-navigation.yaml',
        'https://raw.githubusercontent.com/svcvit/Awesome-Dify-Workflow/main/DSL/mcp-browser-navigation.yaml',
        'app:\n  mode: workflow\n  description: Integrate browser control capabilities with Dify using MCP\n\nnodes:\n  - id: start\n    type: start\n    data:\n      title: Start\n  - id: browser\n    type: tool\n    data:\n      title: Browser Control\n      provider: mcp-browser\n  - id: end\n    type: end\n    data:\n      title: End',
        'abc123def456',
        'This workflow allows Dify to control web browsers through MCP protocol',
        '1.0',
        'workflow',
        5,
        '["start", "tool", "llm", "end"]',
        0,
        1,
        1,
        1250,
        3400,
        45,
        2,
        '2024-12-01T10:00:00Z',
        datetime('now'),
        datetime('now'),
        datetime('now')
    ),

    -- AI Agent Example
    (
        '22222222-2222-2222-2222-222222222222',
        'zhouhui-autonomous-research-agent',
        'Autonomous Research Agent',
        'AI agent that can conduct research on any topic with tool use',
        'agents',
        '["AI Agent", "Research", "Tool Use", "Autonomous"]',
        'zhouhui',
        'research-agent-workflow.yaml',
        'https://github.com/wwwzhouhui/dify-for-dsl/blob/master/research-agent-workflow.yaml',
        'https://raw.githubusercontent.com/wwwzhouhui/dify-for-dsl/master/research-agent-workflow.yaml',
        'app:\n  mode: agent\n  description: Autonomous research agent with multi-step reasoning\n\nnodes:\n  - id: start\n    type: start\n    data:\n      title: Start Research\n  - id: search\n    type: tool\n    data:\n      title: Web Search\n      provider: search\n  - id: analyze\n    type: llm\n    data:\n      title: Analyze Results\n  - id: end\n    type: end\n    data:\n      title: Report',
        'def789ghi012',
        'An AI agent capable of conducting comprehensive research on any topic',
        '1.2',
        'agent',
        8,
        '["start", "tool", "llm", "knowledge", "end"]',
        1,
        1,
        1,
        890,
        2100,
        32,
        1,
        '2024-12-02T15:30:00Z',
        datetime('now'),
        datetime('now'),
        datetime('now')
    ),

    -- RAG Pipeline Example
    (
        '33333333-3333-3333-3333-333333333333',
        'shamspias-pdf-qa-rag',
        'PDF Q&A RAG Pipeline',
        'Upload and query PDF documents using RAG architecture',
        'rag',
        '["RAG", "PDF", "Document Q&A", "Knowledge Base"]',
        'shamspias',
        'flows/pdf-qa-rag.yaml',
        'https://github.com/shamspias/awesome-dify-agents/blob/main/flows/pdf-qa-rag.yaml',
        'https://raw.githubusercontent.com/shamspias/awesome-dify-agents/main/flows/pdf-qa-rag.yaml',
        'app:\n  mode: workflow\n  description: RAG pipeline for PDF document Q&A\n\nnodes:\n  - id: start\n    type: start\n    data:\n      title: Upload PDF\n  - id: extract\n    type: knowledge\n    data:\n      title: Extract Text\n  - id: embed\n    type: knowledge\n    data:\n      title: Create Embeddings\n  - id: query\n    type: llm\n    data:\n      title: Answer Question\n  - id: end\n    type: end\n    data:\n      title: Response',
        'ghi345jkl678',
        'Complete RAG pipeline for processing and querying PDF documents',
        '1.1',
        'workflow',
        6,
        '["start", "knowledge", "llm", "end"]',
        1,
        0,
        1,
        2100,
        5600,
        78,
        0,
        '2024-12-03T09:15:00Z',
        datetime('now'),
        datetime('now'),
        datetime('now')
    ),

    -- Content Creation Example
    (
        '44444444-4444-4444-4444-444444444444',
        'bannylon-social-media-writer',
        'Social Media Content Writer',
        'Generate engaging social media posts for multiple platforms',
        'content',
        '["Content Creation", "Social Media", "Marketing", "Writing"]',
        'bannylon',
        'social-media-writer.yaml',
        'https://github.com/BannyLon/DifyAIA/blob/main/social-media-writer.yaml',
        'https://raw.githubusercontent.com/BannyLon/DifyAIA/main/social-media-writer.yaml',
        'app:\n  mode: workflow\n  description: Create engaging social media content\n\nnodes:\n  - id: start\n    type: start\n    data:\n      title: Topic Input\n  - id: research\n    type: llm\n    data:\n      title: Research Topic\n  - id: write\n    type: llm\n    data:\n      title: Generate Content\n  - id: format\n    type: template\n    data:\n      title: Format for Platform\n  - id: end\n    type: end\n    data:\n      title: Publish Ready',
        'jkl901mno234',
        'Automated social media content generation with platform-specific formatting',
        '1.0',
        'workflow',
        5,
        '["start", "llm", "template", "end"]',
        0,
        1,
        1,
        1650,
        4300,
        56,
        3,
        '2024-12-04T14:20:00Z',
        datetime('now'),
        datetime('now'),
        datetime('now')
    ),

    -- Data Analysis Example
    (
        '55555555-5555-5555-5555-555555555555',
        'winson-sales-data-analyzer',
        'Sales Data Analyzer',
        'Analyze sales data and generate insights with visualizations',
        'data',
        '["Data Analysis", "Sales", "Reports", "Visualization"]',
        'winson',
        'sales-analyzer-dsl.yaml',
        'https://github.com/Winson-030/dify-DSL/blob/main/sales-analyzer-dsl.yaml',
        'https://raw.githubusercontent.com/Winson-030/dify-DSL/main/sales-analyzer-dsl.yaml',
        'app:\n  mode: workflow\n  description: Comprehensive sales data analysis tool\n\nnodes:\n  - id: start\n    type: start\n    data:\n      title: Upload Data\n  - id: process\n    type: code\n    data:\n      title: Process Data\n  - id: analyze\n    type: llm\n    data:\n      title: Generate Insights\n  - id: visualize\n    type: tool\n    data:\n      title: Create Charts\n  - id: report\n    type: template\n    data:\n      title: Generate Report\n  - id: end\n    type: end\n    data:\n      title: Complete',
        'mno567pqr890',
        'Automated sales data analysis with AI-powered insights and visualizations',
        '1.3',
        'workflow',
        7,
        '["start", "code", "llm", "tool", "template", "end"]',
        0,
        1,
        1,
        980,
        2500,
        21,
        1,
        '2024-12-05T11:45:00Z',
        datetime('now'),
        datetime('now'),
        datetime('now')
    ),

    -- Translation Example
    (
        '66666666-6666-6666-6666-666666666666',
        'pgshen-multilang-translator',
        'Multilingual Document Translator',
        'Translate documents between multiple languages with context preservation',
        'translation',
        '["Translation", "Multi-language", "Documents", "Localization"]',
        'pgshen',
        'translator-app-template.yaml',
        'https://github.com/PGshen/dify-app-template/blob/main/translator-app-template.yaml',
        'https://raw.githubusercontent.com/PGshen/dify-app-template/main/translator-app-template.yaml',
        'app:\n  mode: workflow\n  description: Professional document translation service\n\nnodes:\n  - id: start\n    type: start\n    data:\n      title: Document Input\n  - id: detect\n    type: llm\n    data:\n      title: Detect Language\n  - id: translate\n    type: llm\n    data:\n      title: Translate\n  - id: review\n    type: llm\n    data:\n      title: Quality Review\n  - id: format\n    type: template\n    data:\n      title: Format Output\n  - id: end\n    type: end\n    data:\n      title: Translated',
        'pqr890stu345',
        'Professional-grade document translation with AI-powered quality assurance',
        '1.2',
        'workflow',
        6,
        '["start", "llm", "template", "end"]',
        0,
        0,
        1,
        1420,
        3800,
        43,
        2,
        '2024-12-06T16:30:00Z',
        datetime('now'),
        datetime('now'),
        datetime('now')
    );

-- Update category counts
UPDATE categories SET workflow_count = 1 WHERE id = 'mcp';
UPDATE categories SET workflow_count = 1 WHERE id = 'agents';
UPDATE categories SET workflow_count = 1 WHERE id = 'rag';
UPDATE categories SET workflow_count = 1 WHERE id = 'content';
UPDATE categories SET workflow_count = 1 WHERE id = 'data';
UPDATE categories SET workflow_count = 1 WHERE id = 'translation';